version: '3.8'

services:
  db:
    # Используем официальный легковесный образ на базе Alpine
    image: postgres:16-alpine
    container_name: mediadms_postgres
    restart: always
    
    # Подтягиваем переменные из твоего .env файла
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    # Проброс портов: твой кастомный 5531 -> стандартный 5432 внутри контейнера
    ports:
      - "${DB_PORT}:5432"

    # Настройка томов (Volumes)
    volumes:
      # 1. Сохранение данных между перезапусками (как ты и просил)
      - ./pgdata:/var/lib/postgresql/data
      
      # 2. Авто-инициализация: кладем sql скрипт в спец. папку контейнера
      # Все, что лежит в ./init_db/, выполнится при первом старте
      - ./init_db:/docker-entrypoint-initdb.d

    # Ограничение ресурсов (хороший тон для промышленных доков)
    deploy:
      resources:
        limits:
          memory: 1024M